// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnv8_ulVKl4GoCc9Ndv5S34qoSBZqUoCk',
    appId: '1:989012661206:web:4c7b712e2c1f4075b08a77',
    messagingSenderId: '989012661206',
    projectId: 'time-management-app-f4483',
    authDomain: 'time-management-app-f4483.firebaseapp.com',
    storageBucket: 'time-management-app-f4483.appspot.com',
    measurementId: 'G-WRZT1CBCC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-APuN_t0ZI12BaOi5lptyw49TJao5s-s',
    appId: '1:989012661206:android:ad649a63bc856e43b08a77',
    messagingSenderId: '989012661206',
    projectId: 'time-management-app-f4483',
    storageBucket: 'time-management-app-f4483.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUzsp45iryUUAj_VIim-enLXr81S9KKT4',
    appId: '1:989012661206:ios:7080a515abcf0707b08a77',
    messagingSenderId: '989012661206',
    projectId: 'time-management-app-f4483',
    storageBucket: 'time-management-app-f4483.appspot.com',
    iosBundleId: 'com.example.utsMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUzsp45iryUUAj_VIim-enLXr81S9KKT4',
    appId: '1:989012661206:ios:7080a515abcf0707b08a77',
    messagingSenderId: '989012661206',
    projectId: 'time-management-app-f4483',
    storageBucket: 'time-management-app-f4483.appspot.com',
    iosBundleId: 'com.example.utsMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnv8_ulVKl4GoCc9Ndv5S34qoSBZqUoCk',
    appId: '1:989012661206:web:fbc08cad9549c1f9b08a77',
    messagingSenderId: '989012661206',
    projectId: 'time-management-app-f4483',
    authDomain: 'time-management-app-f4483.firebaseapp.com',
    storageBucket: 'time-management-app-f4483.appspot.com',
    measurementId: 'G-4XMX7FW3JR',
  );
}
